apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hello-nfs
spec:
  capacity:
    storage: 10Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    server: 192.168.56.200
    path: /hello
  mountOptions:
    - soft
    - nfsvers=4.2
  claimRef:
    name: pvc-hello-nfs
    namespace: default
