apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1-nfs
spec:
  capacity:
    storage: 10Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    server: 192.168.56.200
    path: /
  mountOptions:
    - soft
    - nfsvers=4.2
