apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-hello-nfs
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
  volumeName: pv-hello-nfs
