apiVersion: batch/v1
kind: Job
metadata:
  name: date
spec:
  template:
    metadata:
    spec:
      containers:
      - command:
        - date
        image: busybox
        name: date
      restartPolicy: Never
