apiVersion: batch/v1
kind: CronJob
metadata:
  name: date
spec:
  jobTemplate:
    metadata:
      name: date
    spec:
      template:
        spec:
          containers:
          - command:
            - date
            image: busybox:1.28
            name: date
          restartPolicy: OnFailure
  schedule: '*/2 14 23 6 *'
