apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.28
        name: nginx
        env:
          - name: STAGE
            value: Kubernetes
          - name: PODIP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: INTERVENTION
            valueFrom:
              configMapKeyRef:
                name: nginx
                key: FORMATION
        envFrom:
          - configMapRef:
              name: nginx
