apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.28
        name: nginx
        readinessProbe:
          httpGet:
            port: 80
            path: /index.html
          periodSeconds: 5
          failureThreshold: 2
        livenessProbe:
          httpGet:
            port: 80
            path: /index.html
          periodSeconds: 10
          failureThreshold: 2
