apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello
  name: hello
  namespace: hello
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello
  type: LoadBalancer
