apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wwwphp
  name: wwwphp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wwwphp
  template:
    metadata:
      labels:
        app: wwwphp
    spec:
      containers:
      - image: nginx:1.28
        name: nginx
        volumeMounts:
          - name: nginx-conf
            mountPath: /etc/nginx/conf.d
          - name: site
            mountPath: /usr/share/nginx/html
      - image: php:8.2-fpm
        name: php
        volumeMounts:
          - name: site
            mountPath: /var/www/html
      
      volumes:
        - name: site
          hostPath:
            path: /home/stagiaire/partage/html
            type: Directory
        - name: nginx-conf
          hostPath:
            path: /home/stagiaire/partage/nginx-conf
            type: Directory
