apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wwwphp
  name: wwwphp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wwwphp
  template:
    metadata:
      labels:
        app: wwwphp
    spec:
      containers:
      - image: nginx:1.28
        name: nginx
        volumeMounts:
          - name: lemp
            mountPath: /etc/nginx/conf.d
            subPath: nginx-conf
          - name: lemp
            mountPath: /usr/share/nginx/html
            subPath: html
      - image: php:8.2-fpm
        name: php
        volumeMounts:
          - name: lemp
            mountPath: /var/www/html
            subPath: html
      
      volumes:
        - name: lemp
          persistentVolumeClaim:
            claimName: pvc1-nfs
